fix: downgrade pyzstd 0.17.0 -> 0.16.2 (#462)
- The pyzstd version 0.17.0 expects libzstd 1.5.7 where the soname is libzstd.so.1.5.7. As a result, an ImportError can occur in some Debian-based distributions due to missing attributes:

ImportError: cannot import name '_ZSTD_c_targetCBlockSize' from 'pyzstd._c._zstd' (/usr/local/lib/python3.12/dist-packages/umu/_vendor/pyzstd/_c/_zstd.cpython-312-x86_64-linux-gnu.so)

- Which breaks our CI when running some tests, so we cannot bump to 0.17.0 yet unless we decide to drop support for those distros.