fix: create temporary directory on subsequent network errors
- In the case where a network error occurs again for the user after resuming from a cached Steam Linux Runtime or Proton file, a shutil.Error will be raised from shutil.move due to the destination path already existing:

raise Error('Destination path '%s' already exists' % real_dst)
shutil.Error: Destination path '/home/deck/.var/app/com.heroicgameslauncher.hgl/cache/umu/SteamLinuxRuntime_sniper.tar.xz.3.0.20250519.130773.parts' already exists

- To handle this case, the cached file needs to be moved to a new temporary directory on the same Linux file system before writing to it.