build: fix FileNotFound in Debian 12 build
- A FileNotFoundError error is raised from the installer module due to the path 'subprojects/urllib3/builddir/urllib3*.whl' being missing:

Traceback (most recent call last):
  File '<frozen runpy>', line 198, in _run_module_as_main
  File '<frozen runpy>', line 88, in _run_code
  File '/usr/lib/python3/dist-packages/installer/__main__.py', line 98, in <module>
    _main(sys.argv[1:], 'python -m installer')
  File '/usr/lib/python3/dist-packages/installer/__main__.py', line 86, in _main
    with WheelFile.open(args.wheel) as source:
  File '/usr/lib/python3.11/contextlib.py', line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File '/usr/lib/python3/dist-packages/installer/sources.py', line 122, in open
    with zipfile.ZipFile(path) as f:
         ^^^^^^^^^^^^^^^^^^^^^
  File '/usr/lib/python3.11/zipfile.py', line 1284, in __init__
    self.fp = io.open(file, filemode)
              ^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'subprojects/urllib3/builddir/urllib3*.whl'

- When the error is raised, the build would continue without failure and the urllib3 module would not be included in the .deb package.