fix: update output path when using zenity (#513)
* fix: update output path when using zenity

- A FileNotFoundError can be raised in umu-launcher when configured to create zenity windows due to the output files being missing:

Traceback (most recent call last):
  File '/usr/lib64/python3.13/shutil.py', line 856, in move
    os.rename(src, real_dst)
    ~~~~~~~~~^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpncu4xb7n/UMU-Proton-9.0-4e.tar.gz.parts' -> '/tmp/tmpncu4xb7n/UMU-Proton-9.0-4e.tar.gz'

- The issue was reported in v1.2.6 and can still be reproduced in v1.2.9 when downloading Proton and/or the Steam Linux Runtime.

* docs: remove UMU_ZENITY from docs

- Creating zenity windows is a feature that will be considered to become obsolete in the next major release. See https://github.com/Open-Wine-Components/umu-launcher/issues/312.