fix: delete license-files key in urllib3 pyproject.toml
- urllib3 uses hatchling as its backend, and the license-files key introduced in https://github.com/urllib3/urllib3/commit/c82d8e506abff905e366ea72ef62c65eed584b17#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711 will cause our workflows to fail due to a TypeError:

TypeError: Field `project.license-files` must be a table

- However, distributions are behind as the TypeError has already been addressed upstream since https://github.com/pypa/hatch/pull/1790