refactor: use tmpfs when sufficiently large (#502)
* refactor: use tmpfs when sufficiently large

- By default, on most Linux distributions, the tmpfs is typically mounted at /tmp and is half the size of the system's RAM. However, depending on how the system is configured, an error can occur when downloading the Steam Linux Runtime and/or Proton:

OSError: [Errno 28]: No space left on device

- This can be a barrier for some users who will be left with no choice but download them out of band. Moreover, the path returned from tempfile.gettempdir may not always be on a tmpfs either. As an improvement, instead of writing all the downloaded files to the system's temporary directory, umu can check if the tmpfs is large enough and otherwise fallback to XDG_CACHE_HOME.

* test: add tests when using tmpfs